# Change build directory, client has our frontend angular code - it requires to reference abi and jsons easily
project_structure:
    build: client/EXPerienceDapp/src/artifacts

### automatically fetch contract sources from Etherscan
# autofetch_sources: True
dotenv: .env

# enable output of development artifacts to load with react
dev_deployment_artifacts: true

# We now need API3's airnode-protocol to use within EXPToken
# for random number generation using API3's QRNG
compiler:
    solc:
        remappings:
            - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@v4.6.0"