# Change build directory, client has our frontend angular code - it requires to reference abi and jsons easily
project_structure:
    build: client/EXPerienceDapp/src/artifacts

### automatically fetch contract sources from Etherscan
# autofetch_sources: True
dotenv: .env

# enable output of development artifacts to load with react
dev_deployment_artifacts: true

# OpenZeppelin contracts are used for ERC20 and ERC721 contracts
# api3dao contracts are used for random number generation using API3 QRNG
# We now need API3's airnode-protocol to use within EXPToken
# for random number generation using API3's QRNG
compiler:
    solc:
        remappings:
            - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0"
            - '@api3=api3dao/airnode@0.6.3/packages/'